<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sable</string>
	</array>
	<key>name</key>
	<string>SableCC</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>Package|Helpers|Tokens|Productions|Ignored Tokens|Abstract Syntax Tree</string>
			<key>name</key>
			<string>constant.other.sable</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?://.*)</string>
			<key>name</key>
			<string>comment.line.double-slash.sable</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?:\{\S+\})</string>
			<key>name</key>
			<string>support.class.sable</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?:\[\S+\])</string>
			<key>name</key>
			<string>support.function.sable</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?:\{ -&gt; .*\})</string>
			<key>name</key>
			<string>constant.character.sable</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.sable</string>
	<key>uuid</key>
	<string>c1172125-0193-4c95-bfe5-44135e904d4c</string>
</dict>
</plist>
